---
overwrite: True

data: "data"
hidden:
 - "hidden_1"
 - "hidden_2"
 - "hidden_3"


nodes:
  # Data nodes
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.ZarrDatasetNodes
      dataset: ${dataloader.dataset}
    attributes: ${graph.attributes.nodes}
  hidden_1:
    node_builder:
      _target_: anemoi.graphs.nodes.TriNodes
      resolution: 5
  hidden_2:
    node_builder:
      _target_: anemoi.graphs.nodes.TriNodes
      resolution: 4
  hidden_3:
    node_builder:
      _target_: anemoi.graphs.nodes.TriNodes
      resolution: 3

edges:
  # Encoder configuration
  - source_name: "data"
    target_name: "hidden_1"
    edge_builders:
    - _target_: anemoi.graphs.edges.CutOffEdges
      cutoff_factor: 0.6
      source_mask_attr_name: null
      target_mask_attr_name: null
    attributes: ${graph.attributes.edges}

    # Decoder configuration
  - source_name: "hidden_1"
    target_name: "data"
    edge_builders:
    - _target_: anemoi.graphs.edges.KNNEdges
      num_nearest_neighbours: 3
      source_mask_attr_name: null
      target_mask_attr_name: null
    attributes: ${graph.attributes.edges}

  # Hierarchical connections: downscale
  - source_name: "hidden_1"
    target_name: "hidden_2"
    edge_builders:
    - ${graph.edge_builders.downscale}
    attributes: ${graph.attributes.edges}

  - source_name: "hidden_2"
    target_name: "hidden_3"
    edge_builders:
    - ${graph.edge_builders.downscale}
    attributes: ${graph.attributes.edges}

  # Hierarchical connections: upscale
  - source_name: "hidden_3"
    target_name: "hidden_2"
    edge_builders:
    - ${graph.edge_builders.upscale}
    attributes: ${graph.attributes.edges}

  - source_name: "hidden_2"
    target_name: "hidden_1"
    edge_builders:
    - ${graph.edge_builders.upscale}
    attributes: ${graph.attributes.edges}

  # Hierarchical connections: same level
  - source_name: "hidden_1"
    target_name: "hidden_1"
    edge_builders:
    - ${graph.edge_builders.process}
    attributes: ${graph.attributes.edges}

  - source_name: "hidden_2"
    target_name: "hidden_2"
    edge_builders:
    - ${graph.edge_builders.process}
    attributes: ${graph.attributes.edges}

  - source_name: "hidden_3"
    target_name: "hidden_3"
    edge_builders:
    - ${graph.edge_builders.process}
    attributes: ${graph.attributes.edges}


#############
edge_builders:
  downscale:
    _target_: anemoi.graphs.edges.CutOffEdges
    cutoff_factor: 1.5
    source_mask_attr_name: null
    target_mask_attr_name: null
  process:
    _target_: anemoi.graphs.edges.MultiScaleEdges
    x_hops: 1
    source_mask_attr_name: null
    target_mask_attr_name: null
  upscale:
    _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 5
    source_mask_attr_name: null
    target_mask_attr_name: null

attributes:
  nodes:
    area_weight:
      _target_: anemoi.graphs.nodes.attributes.SphericalAreaWeights # options: Area, Uniform
      norm: unit-max  # options: l1, l2, unit-max, unit-sum, unit-std
      fill_value: 0
  edges:
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-std
